---
title: "About"
author: "Mike K Smith"
date: "9 November 2016"
output: html_document
---
### Welcome to the DDMoRe Model Description Language (MDL) Community page.
This website will provide a resource for anyone wishing to encode models with MDL, will help you understand MDL structure and features and provides a place for you to log bugs, issues, feature requests and suggestions.

### What is MDL?
MDL is a human writeable and human readable language designed to describe pharmacometric models. It is intended to be largely agnostic about the choice of target tool. MDL should facilitate clear and unambiguous definition of models, with information conveyed in a consistent manner to the PharmML representation and onwards to the target software specific code.

### Where can I find out more about MDL?
The [MDL User Guide and Reference Manual](http://www.ddmore.eu/sites/ddmore/files/instructions/pdf/MDLUserGuide_1.1_PublicRelease_August2016_0.pdf)
is available online in PDF format. 

At the [ddmore.eu](http://ddmore.eu/instructions/user-guides)
website you'll also find instructions for downloading and installing the DDMoRe 
Interoperability Framework Standalone Execution Environment (SEE) demonstrator. 

A [YouTube playlist](https://www.youtube.com/playlist?list=PL_GGUkhbiP3t0Q7wTqkQdMAw7yuC8xWa-) 
is available for videos detailing how to get started with the software.

A set of Use Case examples is provided with the SEE, which are also available on 
[SourceForge](https://sourceforge.net/p/ddmore/use.cases/ci/master/tree/MDL/Product5.1/).

### What is coming on this website?
In the near future we hope to provide: 

* An online wiki format of the MDL User Guide and Reference Manual
* Answers to Frequently Asked Questions (FAQ)
* An issues log for capturing bugs, feature requests and suggestions for MDL
* A walkthrough of the MDL Use Case examples explaining and annotating the code.
* Link to the MDL-Editor software - a cross-platform IDE for writing MDL.

### Authors and Contributors
Mike K Smith [@MikeKSmith](https://github.com/MikeKSmith) is the lead user for MDL.
Stuart Moodie [@stumoodie](https://github.com/stumoodie) is the technical lead for MDL.

### Support or Contact
Issues, bugs, feature requests, suggestions for MDL can be logged via the Issues page of this site. Email contact information will be added very soon.

### Acknowledgements
The research leading to these results has received support from the Innovative Medicines Initiative Joint Undertaking under grant agreement n° 115156, resources of which are composed of financial contribution from the European Union's Seventh Framework Programme (FP7/2007-2013) and EFPIA companies’ in kind contribution. The DDMoRe project is also financially supported by contributions from Academic and SME partners.