---
title: "Production & Development Language Standards"
author: "Mike K Smith"
date: 2017-05-08T10:00:00Z
tags: ["Standards"]
output: html_document
---

**A subgroup of the DDMoRe Language Standards Community is discussing how to 
support production and development of the DDMoRe Language Standards** 

During the IMI DDMoRe project, we developed the DDMoRe Language Standards (MDL,
PharmML, SO) and integrated these with the associated tools libpharmml, libso,
etc. to form the basis of the DDMoRe Interoperability Framework enabling 
modelling and simulation workflow based on the MDL representation of a model
and automated conversion through PharmML to target software and conversion of 
the output back to the Standard Output object and from there back to R.

With the DDMoRe Foundation, we are keen to ensure that the language standards 
are easily maintained and supported going forward and that these form the basis
of solid standards for future development of tools and converters. We propose to
split development into "Production" and "Development" versions of the standards
and tools. This will ensure that the "Production" version is maintained 
according to good practices in software development, while new features can be
examined and tested using the "Development" version.

Stuart Moodie, Maciej Swat, Rikard Nordgren, Nadia Terranova, Vijay Ivaturi and 
Mike K Smith are discussing the pathway to achieving this aim. We would welcome
thoughts, input and discussion from the community on this topic.