---
title: "DDMoRe Language Community"
author: "Mike K Smith"
date: 2017-01-18T11:34:00Z
tags: ["Community"]
output: html_document
---

**Yesterday (17th January 2017) we announced the start of the DDMoRe Language 
Community.**

## What is the DDMoRe Language Community for?
The DDMoRe model exchange standards - the Model Description Language (MDL),
Pharmacometrics Markup Language (PharmML), and Standard Output object (SO) - 
are open-source standards. The IMI DDMoRe project delivered a proof of concept
implementation of an Interoperability Framework which incorporates these 
standards and shows how, having encoded the model using MDL, the modeller can
then perform a complete pharmacometrics workflow (estimation, diagnostics,
prediction / simulation and optimal design) without having to recode the model
for different target software tools.

The DDMoRe Language Community is intended as a forum for discussion of 
the standards, how they can evolve, feature requests, bug reporting, 
finding help etc. It will also work as a hub to share how the standards are 
being used in integrating tools into a unified workflow through conversion 
from and to PharmML, use of the Standard Output object and so on.

The DDMoRe Foundation will continue to have the overview and strategic vision
for the integration of the standards into existing products: 
the Interoperability Framework, DDMoRe Model Repository. But the community can
assist the Foundation in specifying, reviewing, refining new language features
or assisting with existing or new converter tools for the different target 
software that we might want to use within the community.

## How can I contribute to the DDMoRe Language Community?
There are many ways that you can contribute, with a variety of levels of
engagement and commitment. We encourage ***everyone*** to contribute, with 
big **or** small contributions. The ultimate success of these standards depends 
on YOU being engaged, contributing to the community, sharing what you're doing 
with the standards or helping to refine them to meet your needs.

### Language development
The DDMoRe Language standards are integrated through the language converters
employed within the DDMoRe Interoperability Framework. Going forward, the 
the DDMoRe Foundation will aim to incrementally release the languages into 
"production", so that the languages are well aligned and that converters, 
technology and the DDMoRe repository are set up to use this latest version.

But that doesn't stop the community from working on the language standards in 
parallel - having "development" versions, discussing, refining, incorporating
suggestions and fixes where necessary.

The MDL language standards and associated tools are hosted on Github at 
https://github.com/ModelDefinitionLanguage. We encourage the community 
members to join Github, fork the repositories, make changes and then submit a
"pull request" for discussion of the changes. There is a [good primer available 
on Github process](https://guides.github.com/activities/hello-world/).
if you're not familiar with it.

If you want to contribute to documentation of the language standards
(particularly MDL) then the 
[MDL User Guide is now on Github](https://github.com/ModelDefinitionLanguage/MDLUserGuide). 
The guide uses [RStudio's "bookdown"](https://github.com/rstudio/bookdown) 
format - you edit R markdown pages which are then rendered into the online book 
and PDF version.

If you want to contribute to the MDL Community website, to contribute blog posts
"How to..." or "Getting started..." guides, then please pull the "draft" branch of
the website repository, add .Rmd files to the /content/post/ and create a pull 
request for review. Alternatively, send an R markdown file containing your post to 
Mike K Smith (Mike.K.Smith at Pfizer.com).

If you want to raise a bug report, ask a question, make a feature request then
you can raise a [Github Issue on the website repository]
(https://github.com/ModelDefinitionLanguage/website/issues).
We will then reassign this to the appropriate repository and the 
resolution can be discussed and tracked via Github.

### Tool development
If you wish to develop new tools or contribute to development of existing tools
usign the DDMoRe language standards, then we can point you in the direction of
the appropriate technology and associated subject matter experts to help you
get started. If you don't need that assistance, please go right ahead and 
develop away! All we ask is that you respect the license agreements from the 
existing software (most of which uses AGPL, ASL or variants of open-source 
licenses) and we ask that you also keep the community informed what you're 
doing, so that others don't reinvent the wheel and/or could help contribute to
your development.

Any work done on the existing standards and associated toolsets will be 
open-source and we would encourage new development to be similarly open-sourced
so that the community can benefit from and bootstrap off this work.

## How will my contribution be recognised?
If you contribute to the language standards, tools, website, User Guide through
Github, then we'd like to have your Github profile linked via the MDL Community
website. That way, others will know what you've contributed, and can also link 
through to any other work you might be involved in through Github.

We welcome and will recognise ***contribution*** and ***active engagement*** to 
the MDL community. The DDMoRe Foundation is working on how to recognise individual 
contribution to the Foundation, and this will be announced at some point in the
future. 

In the meantime, please do let us know what you think, how you'd like to get
engaged, what kinds of things you might want to do with the standards.

The future is out there!
